name: Run Robot Framework Tests on Windows

on:
  workflow_dispatch:  # Cho phép chạy workflow thủ công
  schedule:
    - cron: '0 17 * * *'  # Chạy tự động mỗi ngày lúc 17:00 UTC

jobs:
  test:
    runs-on: windows-latest  # Chạy trên môi trường Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Cài đặt Robot Framework và các thư viện cần thiết

      - name: Install Google Chrome & ChromeDriver
        run: |
          choco install googlechrome chromedriver -y
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      - name: Run Robot Framework tests
        env:
          WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
          TZ: Asia/Ho_Chi_Minh
        run: |
          if (-not (robot --outputdir results --exclude skip Tests/eBay/FunctionalTestSuite/)) {
              echo "Robot Framework tests failed. Rerunning failed tests..."
              if (Test-Path results/output.xml) {
                  robot --rerunfailed results/output.xml --outputdir results_rerun Tests/eBay/FunctionalTestSuite/ || $true
                  if (Test-Path results_rerun/output.xml) {
                      rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
                  } else {
                      echo "No output.xml file found from rerun. Skipping merge."
                  }
              } else {
                  echo "No output.xml file found. Cannot rerun failed tests."
              }
          }
          echo "Script execution completed"
        shell: pwsh
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3