name: Run Robot Framework Tests on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; fi

      - name: Install Google Chrome & ChromeDriver
        run: |
          choco install googlechrome chromedriver -y
          echo "Chrome Version:"
          google-chrome --version
          echo "ChromeDriver Version:"
          chromedriver --version

      - name: Run Robot Framework tests with retry
        run: |
          echo "Running Robot Framework tests..."
          if (-not (robot --outputdir Results Tests/eBay/FunctionalTestSuite/)) {
              echo "Test failed. Retrying failed tests..."
              if (Test-Path Results/output.xml) {
                  robot --rerunfailed Results/output.xml --outputdir Results_rerun Tests/eBay/FunctionalTestSuite/
              }
          }
        shell: pwsh

      - name: Merge test results
        run: |
          if (Test-Path Results_rerun/output.xml) {
              rebot --output Results/output.xml --log Results/log.html --report Results/report.html --merge Results/output.xml Results_rerun/output.xml
          }
        shell: pwsh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          path: ./Results
          name: robot-test-results
          retention-days: 3