name: Robot Framework Tests

on:
  push:
    branches:
      - master  # Chạy khi có code push vào nhánh chính
  pull_request:
    branches:
      - master  # Chạy khi có pull request đến nhánh chính

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Chọn phiên bản Python cần dùng

      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          sudo apt-get install -y chromium-chromedriver
          chromedriver --version

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Kiểm tra nếu có file requirements.txt thì mới cài đặt

      - name: Run Robot Framework Tests
        run: |
          robot -d Results Tests/eBay/FunctionalTestSuite/
        env:
          ROBOT_BROWSER: chrome
          ROBOT_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-profile"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Results/  # Lưu kết quả test để download từ GitHub Actions