name: Robot Framework Tests

on:
  push:
    branches:
      - master  # Chạy khi có code push vào nhánh chính
  pull_request:
    branches:
      - master  # Chạy khi có pull request đến nhánh chính

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Phiên bản Python cần dùng

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Cài đặt Robot Framework và các thư viện cần thiết

      - name: Run Robot Framework Tests
        run: robot -d Results Tests/  # Chạy test và lưu kết quả vào thư mục Results

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Results/  # Lưu kết quả test để download từ GitHub Actions